import tables

rm_table_sql = f"""DROP TABLE IF EXISTS {tables.DOF};"""

create_table_sql = f"""CREATE TABLE {tables.DOF} (
    id INTEGER PRIMARY KEY,
    year INTEGER,
    date_issued TEXT,
    longitude TEXT,
    autex_release_date TEXT,
    situation TEXT,
    operator_name TEXT,
    common_name TEXT,
    volume_remaining TEXT,
    origin_name TEXT,
    state TEXT,
    area TEXT,
    origninal_authorization TEXT,
    original_authorized_volume TEXT,
    autex_id TEXT,
    scientific_name TEXT,
    last_update TEXT,
    operator_ctf TEXT,
    autex_type TEXT,
    operator_id TEXT,
    unit TEXT,
    city TEXT,
    autex_date_valid TEXT,
    product TEXT,
    issuing_authority TEXT,
    latitude TEXT
);"""

sql = f"""INSERT INTO {tables.DOF} (
    id,
    year,
    date_issued,
    longitude,
    autex_release_date,
    situation,
    operator_name,
    common_name,
    volume_remaining,
    origin_name,
    state,
    area,
    original_authorization,
    original_authorized_volume,
    autex_id,
    scientific_name,
    last_update,
    operator_ctf,
    autex_type,
    operator_id,
    unit,
    city,
    autex_date_valid,
    product,
    issuing_authority,
    latitude) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);"""