
import tables

rm_table_sql = f"""DROP TABLE {tables.POA};"""

create_table_sql = f"""CREATE TABLE {tables.POA} (
    id INTEGER PRIMARY KEY,
    product TEXT,
    common_name TEXT,
    scientific_name TEXT,
    volume REAL,
    analyst_institution  TEXT,
    date_valid TEXT,
    plot_car_id TEXT,
    state TEXT,
    city TEXT,
    unit_latitude TEXT,
    unit_longitude TEXT,
    unit_area REAL,
    operation_latitude TEXT,
    operation_longitude TEXT,
    production_unit TEXT,
    date_issued TEXT,
    date_effective TEXT,
    authorization TEXT,
    registration TEXT,
    pmfs_authorization_boundry TEXT,
    technician_name TEXT,
    technician_number INTEGER,
    technician_grade TEXT,
    operator_name TEXT,
    operator_id TEXT,
    managed_area REAL,
    volume_equation TEXT,
    inventory_method  TEXT,
    last_referenced TEXT,
    last_updated TEXT,
    legal_status TEXT,
    boundry TEXT,
    situation TEXT,
    business_type TEXT,
    business_name TEXT,
    assessment TEXT,
    origninal_authorization TEXT,
    last_processed TEXT
);"""    

sql = f"""INSERT INTO {tables.POA} (
    id,
    product, 
    common_name, 
    scientific_name, 
    volume, 
    analyst_institution, 
    date_valid, 
    plot_car_id,
    state,
    city,
    unit_latitude,
    unit_longitude,
    unit_area,
    operation_latitude,
    operation_longitude,
    production_unit,
    date_issued,
    date_effective,
    authorization,
    registration,
    pmfs_authorization_boundry, 
    technician_name,
    technician_number,
    technician_grade,
    operator_name,
    operator_id,
    managed_area,
    volume_equation,
    inventory_method,
    last_referenced,
    last_updated,
    legal_status,
    boundry,
    situation,
    business_type,
    business_name,
    assessment,
    origninal_authorization,
    last_processed)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);"""
