import tables

rm_table_sql = f"""DROP TABLE IF EXISTS {tables.TRANSPORT};"""

create_table_sql = f"""CREATE TABLE {tables.TRANSPORT} (
    id INTEGER PRIMARY KEY,
    import_declaration_id TEXT,
    autesp_id TEXT,
    dof_valid_start_date TEXT,
    dof_control_code TEXT,
    origin_certification_date TEXT,
    consolidated_value REAL,
    name_of_shipper TEXT,
    receiver_ctf TEXT,
    receiver_id TEXT,
    units TEXT,
    autex_date_valid TEXT,
    country_of_origin TEXT,
    dof_serial_id TEXT,
    state_of_origin TEXT,
    property_origin_name TEXT,
    origin_latitude REAL,
    destination_city TEXT,
    port_city TEXT,
    origin_longitude REAL,
    product TEXT,
    destination_country TEXT,
    dof_system_of_origin TEXT,
    origin_city TEXT,
    destination_state TEXT,
    port_of_entry_name TEXT,
    dof_date_issued TEXT,
    port_of_exit_name TEXT,
    shipper_ctf_id TEXT,
    dof_final_transaction TEXT,
    volume REAL,
    tracking_number TEXT,
    destination_property_name TEXT,
    port_state TEXT,
    year TEXT,
    dof_last_transaction_date TEXT,
    destination_latitude REAL,
    last_tracking_access TEXT,
    destination_longitude REAL,
    dof_validity_expiration_date TEXT,
    origin_certification_agency TEXT,
    origin_issuer_of_import_declaration TEXT,
    destination_receiver_name TEXT,
    autex_serial_id TEXT,
    transport_route TEXT,
    species_name TEXT,
    internal_dof_offer_id TEXT,
    autesp_date_valid TEXT,
    shipper_id TEXT,
    original_authorization_id TEXT,
    origin_type TEXT,
    scientific_name TEXT,
    autesp_issuing_organization TEXT,
    autex_type TEXT,
    import_declaration_date_value TEXT,
    item_value REAL
    )"""

sql = f"""INSERT INTO {tables.TRANSPORT} (
    id,
    import_declaration_id,
    autesp_id,
    dof_valid_start_date,
    dof_control_code,
    origin_certification_date,
    consolidated_value,
    name_of_shipper,
    receiver_ctf,
    receiver_id,
    units,
    autex_date_valid,
    country_of_origin,
    dof_serial_id,
    state_of_origin,
    property_origin_name,
    origin_latitude,
    destination_city,
    port_city,
    origin_longitude,
    product,
    destination_country,
    dof_system_of_origin,
    origin_city,
    destination_state,
    port_of_entry_name,
    dof_date_issued,
    port_of_exit_name,
    shipper_ctf_id,
    dof_final_transaction,
    volume,
    tracking_number,
    destination_property_name,
    port_state,
    year,
    dof_last_transaction_date,
    destination_latitude,
    last_tracking_access,
    destination_longitude,
    dof_validity_expiration_date,
    origin_certification_agency,
    origin_issuer_of_import_declaration,
    destination_receiver_name,
    autex_serial_id,
    transport_route,
    species_name,
    internal_dof_offer_id,
    autesp_date_valid,
    shipper_id,
    original_authorization_id,
    origin_type,
    scientific_name,
    autesp_issuing_organization,
    autex_type,
    import_declaration_date_value,
    item_value
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);"""