AUTEX_DIR       = 'Autex'
DATA_DIR        = 'data-files'
DATABASE_DIR    = 'databases'
SQL_DATABASE    = 'forestry.db'
PMFS_DIR        = 'PMFS'
PMFS_URL        = 'https://dadosabertos.ibama.gov.br/dados/SINAFLOR/pmfs/AmazoniaLegal/pmfsAmazoniaLegal_json.zip'
